import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../../theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 15, backgroundColor: COLORS.white, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  headerTitle: { fontFamily: FONTS.heading, fontSize: 18, color: COLORS.navy, fontWeight: 'bold' },
  backBtn: { padding: 5 }, headerActionBtn: { padding: 5 }, listContainer: { padding: 15 },
  emptyText: { textAlign: 'center', marginTop: 40, fontFamily: FONTS.body, color: COLORS.gray1 },
  topicCard: { backgroundColor: COLORS.white, padding: 15, borderRadius: 12, marginBottom: 15, borderWidth: 1, borderColor: COLORS.border },
  topicHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  authorRow: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 30, height: 30, borderRadius: 15, backgroundColor: COLORS.green, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  avatarText: { color: COLORS.white, fontFamily: FONTS.heading, fontWeight: 'bold', fontSize: 14 },
  authorName: { fontFamily: FONTS.body, color: COLORS.gray1, fontSize: 14 },
  topicActions: { flexDirection: 'row', alignItems: 'center' },
  topicTitle: { fontFamily: FONTS.heading, fontSize: 16, fontWeight: 'bold', color: COLORS.navy, marginBottom: 5 },
  topicDesc: { fontFamily: FONTS.body, fontSize: 14, color: COLORS.gray1, lineHeight: 20 },
  hasAttachmentText: { fontFamily: FONTS.body, fontSize: 12, color: COLORS.green, marginTop: 10 },
  votesRow: { flexDirection: 'row', marginTop: 15, gap: 15 },
  voteBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 5, paddingHorizontal: 10, backgroundColor: COLORS.bg, borderRadius: 8 },
  voteText: { fontSize: 14, color: COLORS.navy, opacity: 0.7 }, voteActive: { opacity: 1, fontWeight: 'bold', color: COLORS.navy },
  createContainer: { padding: 20 },
  label: { fontFamily: FONTS.heading, fontSize: 14, color: COLORS.navy, fontWeight: 'bold', marginBottom: 8, marginTop: 15 },
  input: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, padding: 15, fontFamily: FONTS.body, fontSize: 14, color: COLORS.navy },
  textArea: { height: 120 }, imgPickerRow: { flexDirection: 'row', alignItems: 'center', marginTop: 20, marginBottom: 30 },
  imgPickerBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border, padding: 10, borderRadius: 8 },
  imgPickerTxt: { marginLeft: 8, fontFamily: FONTS.body, fontSize: 14, color: COLORS.navy },
  imgPreviewCont: { marginLeft: 15, position: 'relative' }, imgPreview: { width: 60, height: 60, borderRadius: 8 },
  imgRemoveBtn: { position: 'absolute', top: -10, right: -10, backgroundColor: 'red', width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  imgRemoveTxt: { color: 'white', fontWeight: 'bold', fontSize: 12, textAlign: 'center' },
  submitBtn: { backgroundColor: COLORS.green, padding: 15, borderRadius: 8, alignItems: 'center' },
  submitBtnTxt: { color: COLORS.white, fontFamily: FONTS.heading, fontWeight: 'bold', fontSize: 16 },
  threadContainer: { padding: 15, paddingBottom: 40 },
  opCard: { backgroundColor: COLORS.white, padding: 15, borderRadius: 12, marginBottom: 20, borderWidth: 1, borderColor: COLORS.border },
  msgText: { fontFamily: FONTS.body, fontSize: 15, color: COLORS.navy, lineHeight: 22, marginTop: 10 },
  msgImgFull: { width: '100%', height: 200, marginTop: 15, borderRadius: 8 },
  separator: { height: 1, backgroundColor: COLORS.border, marginVertical: 15 },
  commentsTitle: { fontFamily: FONTS.heading, fontSize: 16, fontWeight: 'bold', color: COLORS.navy, marginBottom: 15 },
  commentCard: { backgroundColor: COLORS.white, padding: 15, borderRadius: 12, marginBottom: 10, marginLeft: 20, borderWidth: 1, borderColor: COLORS.border },
  commentAuthorName: { fontFamily: FONTS.body, color: COLORS.gray1, fontSize: 13 },
  msgImgSmall: { width: 100, height: 100, marginTop: 10, borderRadius: 8 },
  commentInputBox: { backgroundColor: COLORS.white, borderTopWidth: 1, borderTopColor: COLORS.border, padding: 10 },
  commentInputRow: { flexDirection: 'row', alignItems: 'center' }, attachBtn: { padding: 10 },
  commentInput: { flex: 1, backgroundColor: COLORS.bg, borderRadius: 20, paddingHorizontal: 15, paddingVertical: 10, minHeight: 40, maxHeight: 100, fontFamily: FONTS.body, color: COLORS.navy },
  sendBtn: { backgroundColor: COLORS.green, width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginLeft: 10 },
  imgPreviewContSmall: { position: 'relative', width: 60, height: 60, marginBottom: 10, marginLeft: 50 },
  imgPreviewSmall: { width: 60, height: 60, borderRadius: 8 },
  imgRemoveBtnSmall: { position: 'absolute', top: -5, right: -5, backgroundColor: 'red', width: 20, height: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  imgRemoveTxtSmall: { color: 'white', fontWeight: 'bold', fontSize: 10, lineHeight: 10, textAlign: 'center' }
});
