export const ENGINEERING_CONSTANTS = {
  CONVERSIONS: {
    BAR_TO_MCA: 10.2,
  },
  TOLERANCES: {
    HP_MIN_FACTOR: 0.60,
    HP_MAX_FACTOR: 1.50,
    CAUDAL_QMAX_MIN_FACTOR: 0.60,
    CAUDAL_QMAX_MAX_FACTOR: 4.0,
    ALTURA_HMAX_MIN_FACTOR: 0.60,
    CURVA_H_MIN_FACTOR: 0.65,
  },
  ELECTRICAL: {
    MONOPHASE_MAX_HP_WARNING: 3.5,
  }
};
